name: Version Bump and Changelog Update

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog description for this version (use ; to separate lines)'
        required: true
        default: ''
      version_type:
        description: 'Version to bump'
        required: true
        default: 'beta'
        type: choice
        options: ['major', 'minor', 'patch', 'beta']

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions on the script
        run: |
          chmod +x ./bump_version.sh

      - name: Bump version and update changelog
        run: |
          ./bump_version.sh "${{ github.event.inputs.changelog }}" "${{ github.event.inputs.version_type }}"

      - name: Commit changes
        run: |
          git config --global user.name "digia-version-up-bot"
          git config --global user.email "digia-version-up-bot@digia.github.com"
          git add .
          git status
          git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
          git push

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get
      # - name: Generate code
      #   run: dart run build_runner build --delete-conflicting-outputs
      # - name: Check Publish Warnings
      #   run: dart pub publish --dry-run
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.PUB_DEV_CREDS }}
          flutter: true
          skipTests: true